[project]
name = "pystrat"
version = "1.0.0"
description = "Sratagem Pick for Helldivers 2 inspired by hellbuddy"
requires-python = ">=3.14"
dependencies = [
    "pillow",
    "pyinstaller>=6.18.0",
    "svglib>=1.6.0",
    "reportlab>=4.4.4",
]

[project.scripts]
build-exe = "build_exe:main"
