[project]
name = "pystrat"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "cairosvg",
    "pillow",
    "pycairo>=1.29.0",
    "pyinstaller>=6.18.0",
    "svglib>=1.6.0",
]

[project.scripts]
build-exe = "build_exe:main"
